[cursor]
color = 1d262a

[colors]
foreground = e7ebed
background = 1d262a

# Black
regular0 = 1d262a
bright0 = a1b0b8

# Red
regular1 = fc3841
bright1 = fc3841

# Green
regular2 = 5cf164
bright2 = 5cf164

# Yellow
regular3 = fed032
bright3 = fed032

# Blue
regular4 = 37b6ff
bright4 = 37b6ff

# Magenta
regular5 = ff37ff
bright5 = ff37ff

# Cyan
regular6 = 59ffd1
bright6 = 59ffd1

# White
regular7 = e7ebed
bright7 = e7ebed
